Kodai/spe 5 create role assignment UI page
LaunchUpCorp/Speakers-corner pull request #2
Opened 2023-05-02 06:52 UTC by khishh

## Pull Request Title (Using conventional commit Standard)

### Type of Change

- [x] New Feature
- [ ] Bug Fix
- [ ] Refactoring
- [ ] Optimization
- [ ] Documentation Update
- [ ] DevOps

### Description

Add the initial point for Role Assignment page along with adding react mui dependency.

Fixes #(issue)

### Testing Instructions

Please provide step-by-step instructions for how to manually test the changes. Be sure to include any relevant URLs, input data, or other information necessary for testing.

### Screenshots (optional)

If applicable, add screenshots to help explain your changes. This can be particularly helpful for frontend and design-related changes. Please provide screenshots for different devices and screen sizes (Mobile, Tablet, and Desktop) if possible.

#### Desktop

![Desktop Screenshot](https://user-images.githubusercontent.com/60908906/235599017-95fd67cb-a61c-4b38-8ff5-71113cb04c21.png)

#### Tablet

![Tablet Screenshot](https://user-images.githubusercontent.com/60908906/235598984-3e85fe8d-6168-4dd1-b224-ab7d32359187.png)

#### Mobile

![Mobile Screenshot](https://user-images.githubusercontent.com/60908906/235598926-26b4169e-0714-47d3-b712-0d118b0eb617.png)

### Deployment Considerations (optional)

If applicable, please provide any deployment considerations or requirements that are necessary for this change, such as database migrations, environment variables, or other required services.

### Checklist (delete irrelevant items)

- [x] I have followed coding standards and best practices.
- [x] My changes generate no new warnings or errors.
- [x] I have manually tested my changes.

2023-05-02 18:28 UTC, m-sekander approved these changes
LGTM!

2023-05-02 23:11 UTC, YoussefLaunchUp requested changes
Good work, small change needed

2023-05-02 23:11 UTC, YoussefLaunchUp commented on client/src/views/RoleAssignmentPage.tsx
Please change the folder structure to be consistent with the rest of the project.
https://github.com/LaunchUpCorp/Speakers-corner/pull/3#pullrequestreview-1409997214

2023-05-03 18:27 UTC, khishh commented on client/src/views/RoleAssignmentPage.tsx
Done!

2023-05-03 19:07 UTC, YoussefLaunchUp requested changes
small change requested

2023-05-03 19:07 UTC, YoussefLaunchUp commented on client/src/views/RoleAssignmentPage/index.tsx
This should be in the page folder not views

2023-05-03 20:20 UTC, YoussefLaunchUp approved these changes
Great work

2023-05-03 21:03 UTC, m-sekander commented
Hey Kodai, looks like you forgot to add the header to the page. For reference, check out my pull request [SPE-14] if you want to see how I used it.

2023-05-03 21:04 UTC, m-sekander requested changes
See comment above

2023-05-03 21:09 UTC, m-sekander commented
Oh and just want to note if this is a modal, I suppose it wouldn't need the header. Lmk what you think, and I can revert the change request. @khishh

2023-05-04 02:50 UTC, m-sekander approved these changes
LGTM!

2023-05-04 03:00 UTC, merged